In [1]:
from bs4 import BeautifulSoup
from fuzzywuzzy import fuzz
import pandas as pd
import numpy as np
import time
import requests

In [2]:
restaurant_name = 'THE ELK'
location_name = '128 CHARLES ST MANHATTAN'

In [3]:
def fetch_restaurant(restaurant_name, location_name):
    
    from bs4 import BeautifulSoup
    from fuzzywuzzy import fuzz
    import pandas as pd
    import numpy as np
    import time
    import requests
    
    error_code = 0
    
    n = 0
    while(n < 100):
        time.sleep(np.random.uniform(1, 3))
        search_link = 'https://www.yelp.com/search?find_desc=' + restaurant_name + '&find_loc=' + location_name + '&ns=1'
        try:
            search_content = BeautifulSoup(requests.get(search_link).text)
        except:
            error_code = -1
            return (None, None, None, None, error_code)
        fetched_restaurants = search_content.find_all('a', {'class': "lemon--a__373c0__1_OnJ link__373c0__29943 link-color--blue-dark__373c0__1mhJo link-size--inherit__373c0__2JXk5"})
        if fetched_restaurants != []:
            break
        n += 1
    
    if n == 100:
        error_code = -2
        return (None, None, None, None, error_code)

    del n 
    
    similarity = np.zeros(len(fetched_restaurants), dtype = 'int')
    for fetched_restaurant_index, fetched_restaurant in enumerate(fetched_restaurants):
        similarity[fetched_restaurant_index] = fuzz.ratio(restaurant_name.strip().lower(), fetched_restaurant.get_text().strip().lower())
    
    fetched_restaurant = fetched_restaurants[similarity.argmax()].get_text().strip()
    similarity_index = similarity.max()
    
    n_reviews = 0
    
    try:
        restaurant_link = 'https://www.yelp.com' + fetched_restaurants[similarity.argmax()].attrs['href'].split('?')[0] + '?start=' + str(n_reviews)
        restaurant_content = BeautifulSoup(requests.get(restaurant_link).text)
    except:
        error_code = -3
        return (None, None, None, None, error_code)
    
    overall_rating = restaurant_content.find('div', {'class': 'biz-rating biz-rating-very-large clearfix'}).find_next().attrs['title'].strip().split()[0].strip()
    overall_reviews = restaurant_content.find('span', {'class': 'review-count rating-qualifier'}).get_text().strip().split(' ')[0].strip()

    price_range = restaurant_content.find('dd', {'class': 'nowrap price-description'}).get_text().strip()
    health_score = restaurant_content.find('dd', {'class': 'nowrap health-score-description'}).get_text().strip()

    attributes_content = restaurant_content.find_all('dd')
    attributes = []
    flag = False
    for attribute in attributes_content:
        if attribute.get_text().strip() in ['Yes', 'No']:
            flag = True
        if flag == True:
            attributes.append(attribute.get_text().strip())
    del flag

    attributes = pd.Series(attributes, index = ['Takes_Reservations', 
                                                'Delivery', 
                                                'Take_out', 
                                                'Accepts_Credit_Cards',
                                                'Good_For',
                                                'Parking',
                                                'Bike_Parking',
                                                'Good_for_Kids',
                                                'Good_for_Groups',
                                                'Attire',
                                                'Ambience',
                                                'Noise_Level',
                                                'Alcohol',
                                                'Outdoor_Seating',
                                                'WiFi',
                                                'Has_TV',
                                                'Waiter_Service',
                                                'Caters',
                                                'Good_for_Working',
                                                'Gender_Neutral_Restrooms',
                                               ])
    
    attributes = attributes.append(pd.Series({'price_range': price_range, 
                                              'health_score': health_score, 
                                              'overall_rating': overall_rating, 
                                              'overall_reviews': overall_reviews}))
    
    reviewer = pd.DataFrame({'er_name':[],
                             'er_location':[],
                             'er_freinds':[],
                             'er_reviews':[],
                             'er_photos':[],
                             'er_rating':[],
                             'er_date':[],
                             'er_text':[],
                             'er_useful':[],
                             'er_funny':[],
                             'er_cool':[]
                            })
    
    error_code = ""
    
    while(n_reviews < 20000):
        try:
            reviews = restaurant_content.find_all('div', {'class':'review review--with-sidebar'})
            if reviews == []:
                break
            for review in reviews:
                text_tag = review.find('p')
                if text_tag.attrs['lang'].strip() != 'en':
                    continue
                er_text = text_tag.get_text().strip()
                er_name = review.find('a', {'class': 'user-display-name js-analytics-click'}).get_text().strip()
                er_location = review.find('li', {'class': 'user-location responsive-hidden-small'}).get_text().strip()
                try:
                    er_friends = review.find('li', {'class': 'friend-count responsive-small-display-inline-block'}).get_text().strip().split(' ')[0].strip()
                except:
                    er_friends = 0
                try:
                    er_reviews = review.find('li', {'class': 'review-count responsive-small-display-inline-block'}).get_text().strip().split(' ')[0].strip()
                except:
                    er_reviews = 0
                try:
                    er_photos = review.find('li', {'class': 'photo-count responsive-small-display-inline-block'}).get_text().strip().split(' ')[0].strip()
                except:
                    er_photos = 0
                er_rating = review.find('div', {'class': 'biz-rating biz-rating-large clearfix'}).find_next().find_next().attrs['title'].strip().split(' ')[0].strip()
                er_date = review.find('span', {'class': 'rating-qualifier'}).get_text().strip()
                statistics = review.find_all('span', {'class': 'count'})
                er_useful = statistics[0].get_text().strip()
                er_funny =  statistics[1].get_text().strip()
                er_cool = statistics[2].get_text().strip()
                reviewer = reviewer.append({'er_name': er_name,
                                            'er_location': er_location,
                                            'er_freinds': er_friends,
                                            'er_reviews': er_reviews,
                                            'er_photos': er_photos,
                                            'er_rating': er_rating,
                                            'er_date': er_date,
                                            'er_text': er_text,
                                            'er_useful': er_useful,
                                            'er_funny': er_funny,
                                            'er_cool': er_cool
                                }, ignore_index = True)
        except:
            error_code = error_code + '/' + str(n_reviews)
        n_reviews += 20
        time.sleep(np.random.uniform(1, 3))
        restaurant_link = 'https://www.yelp.com' + fetched_restaurants[similarity.argmax()].attrs['href'].split('?')[0] + '?start=' + str(n_reviews)
        restaurant_content = BeautifulSoup(requests.get(restaurant_link).text)
    return (attributes, reviewer, fetched_restaurant, similarity_index, error_code)

In [4]:
(attributes, reviewer, fetched_restaurant, similarity_index, error_code) = fetch_restaurant(restaurant_name, location_name)

In [6]:
error_code

''

In [6]:
import pandas as pd
import numpy as np

In [7]:
raw_data = pd.read_csv('../Data/NYC_Rest_Inspect.csv')
raw_data['INSPECTION DATE'] = pd.to_datetime(raw_data['INSPECTION DATE'], format = '%m/%d/%Y')
raw_data['GRADE DATE'] = pd.to_datetime(raw_data['GRADE DATE'], format = '%m/%d/%Y')
raw_data['RECORD DATE'] = pd.to_datetime(raw_data['RECORD DATE'], format = '%m/%d/%Y')
data = raw_data[ (raw_data["BORO"] == "MANHATTAN") & (raw_data["CUISINE DESCRIPTION"] == "American") ]

In [8]:
test = data.head()
test

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE
6,50008995,THE ELK,MANHATTAN,128,CHARLES ST,10014.0,2129334780,American,2018-04-02,Violations were cited in the following area(s).,06D,"Food contact surface not properly washed, rins...",Critical,31.0,NaN,NaT,2018-11-12,Cycle Inspection / Initial Inspection
12,50071738,FUEL GRILL AND JUICE BAR,MANHATTAN,683,9TH AVE,10036.0,2126494664,American,2018-03-07,Violations were cited in the following area(s).,04L,Evidence of mice or live mice present in facil...,Critical,12.0,A,2018-03-07,2018-11-12,Pre-permit (Operational) / Re-inspection
16,40364389,OLD TOWN BAR & RESTAURANT,MANHATTAN,45,EAST 18 STREET,10003.0,2125296732,American,2018-10-11,Violations were cited in the following area(s).,08A,Facility not vermin proof. Harborage or condit...,Not Critical,12.0,A,2018-10-11,2018-11-12,Cycle Inspection / Re-inspection
24,40949462,CUCINA & COMPANY,MANHATTAN,200,PARK AVENUE,10017.0,2126822700,American,2018-03-23,Violations were cited in the following area(s).,06A,Personal cleanliness inadequate. Outer garment...,Critical,7.0,A,2018-03-23,2018-11-12,Cycle Inspection / Initial Inspection
31,40392668,LUCYS,MANHATTAN,135,AVENUE A,10009.0,2126733824,American,2014-09-18,Violations were cited in the following area(s).,08C,Pesticide use not in accordance with label or ...,Not Critical,9.0,A,2014-09-18,2018-11-12,Cycle Inspection / Initial Inspection

In [24]:
search_link = 'https://www.yelp.com/search?find_desc=' + restaurant_name + '&find_loc=' + location_name + '&ns=1'
search_link

'https://www.yelp.com/search?find_desc=THE ELK&find_loc=128+CHARLES+ST+MANHATTAN&ns=1'

In [9]:
test

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE
6,50008995,THE ELK,MANHATTAN,128,CHARLES ST,10014.0,2129334780,American,2018-04-02,Violations were cited in the following area(s).,06D,"Food contact surface not properly washed, rins...",Critical,31.0,NaN,NaT,2018-11-12,Cycle Inspection / Initial Inspection
12,50071738,FUEL GRILL AND JUICE BAR,MANHATTAN,683,9TH AVE,10036.0,2126494664,American,2018-03-07,Violations were cited in the following area(s).,04L,Evidence of mice or live mice present in facil...,Critical,12.0,A,2018-03-07,2018-11-12,Pre-permit (Operational) / Re-inspection
16,40364389,OLD TOWN BAR & RESTAURANT,MANHATTAN,45,EAST 18 STREET,10003.0,2125296732,American,2018-10-11,Violations were cited in the following area(s).,08A,Facility not vermin proof. Harborage or condit...,Not Critical,12.0,A,2018-10-11,2018-11-12,Cycle Inspection / Re-inspection
24,40949462,CUCINA & COMPANY,MANHATTAN,200,PARK AVENUE,10017.0,2126822700,American,2018-03-23,Violations were cited in the following area(s).,06A,Personal cleanliness inadequate. Outer garment...,Critical,7.0,A,2018-03-23,2018-11-12,Cycle Inspection / Initial Inspection
31,40392668,LUCYS,MANHATTAN,135,AVENUE A,10009.0,2126733824,American,2014-09-18,Violations were cited in the following area(s).,08C,Pesticide use not in accordance with label or ...,Not Critical,9.0,A,2014-09-18,2018-11-12,Cycle Inspection / Initial Inspection

In [4]:
def fetch_restaurants(data):
    attributes_ls = []
    reviewer_ls = []
    info = pd.DataFrame({'CAMIS':[],
                         'DBA':[],
                         'fetched_restaurant':[],
                         'similarity_index':[],
                         'error_code':[]
                        })
    for index, row in data.iterrows():
        restaurant_name = row['DBA']
        location_name = row['BUILDING'] + ' ' + row['STREET'] + ' ' + row['BORO']
        (attributes, reviewer, fetched_restaurant, similarity_index, error_code) = fetch_restaurant(restaurant_name, location_name)
        attributes.rename(row['CAMIS'], inplace = True)
        attributes_ls.append(attributes)
        reviewer.to_csv(str(row['CAMIS']) + '.csv')
        info = info.append({'CAMIS': row['CAMIS'],
                            'DBA': row['DBA'],
                            'fetched_restaurant': fetched_restaurant,
                            'similarity_index': similarity_index,
                             'error_code': error_code
                           }, ignore_index = True)
    pd.DataFrame(attributes_ls).to_csv('attributes.csv', mode = 'a', header = False)
    info.to_csv('info.csv', mode = 'a', header = False)

In [10]:
fetch_restaurants(test)

ValueError: Length of passed values is 16, index implies 20

In [12]:
for index, row in test.iterrows():
        restaurant_name = row['DBA']
        location_name = row['BUILDING'] + ' ' + row['STREET'] + ' ' + row['BORO']
        print(restaurant_name)
        print(location_name)

THE ELK
128 CHARLES ST MANHATTAN
FUEL GRILL AND JUICE BAR
683 9TH AVE MANHATTAN
OLD TOWN BAR & RESTAURANT
45 EAST   18 STREET MANHATTAN
CUCINA & COMPANY
200 PARK AVENUE MANHATTAN
LUCYS
135 AVENUE A MANHATTAN

In [18]:
x
x.rename('d', inplace = True)

a    1
b    2
Name: d, dtype: int64